version: "3.7"

services:
  localstack:
    image: localstack/localstack
    hostname: localstack
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4510-4559:4510-4559" # external service port range
      - "4566:4566" # LocalStack Edge Proxy
    environment:
      - DEBUG=true
      - DATA_DIR=/tmp/data
      - LAMBDA_EXECUTOR=local
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  backend:
    build: ../docker
    hostname: backend
    container_name: backend
    restart: unless-stopped
    environment:
      IS_OFFLINE: 1
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "5678:5678"
      - "8000:8000"
    command: >
      bash -c "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ../../:/code
